"""Add Review Model

Revision ID: febbe4b6c3fe
Revises: 5dbb715bdb26
Create Date: 2023-12-08 23:14:37.887318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febbe4b6c3fe'
down_revision = '5dbb715bdb26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
